export type CreditCardPaymentParams = {
  Version?: "1.1" | "2.0";
  MerchantID?: string;
  P3D?: 0 | 1;
  NotifyURL?: string;
  ReturnURL?: string;
  MerchantOrderNo: string;
  Amt: number;
  ProdDesc: string;
  PayerEmail: string;
  Inst?: 0 | 3 | 6 | 12 | 18 | 24 | 30;
  Red?: 0 | 1;
  CardAE?: 0 | 1;
  CardNo?: string;
  Exp?: string;
  CVC?: string;
  APPLEPAY?: string;
  APPLEPAYTYPE?: "01" | "02";
  ANDROIDPAY?: string;
  SAMSUNGPAY?: string;
  NTCB?: 0 | 1;
  NTCBArea?: string;
  NTCBStart?: string;
  NTCBEnd?: string;
  TokenValue?: string;
  TokenTerm?: string;
  TokenSwitch?: "on" | "get";
  TokenLife?: string;
};