export type GetPaymentFormHTMLParams = {
  Version?: string;
  LangType?: "zh-tw" | "en" | "jp";
  MerchantOrderNo: string;
  Amt: number;
  ItemDesc: string;
  TradeLimit?: number;
  ExpireDate?: string;
  ReturnURL?: string;
  NotifyURL?: string;
  CustomerURL?: string;
  ClientBackURL?: string;
  Email?: string;
  EmailModify?: 0 | 1;
  LoginType?: 0 | 1;
  OrderComment?: string;
  CREDIT?: 0 | 1;
  CREDITAE?: 0 | 1;
  APPLEPAY?: 0 | 1;
  ANDROIDPAY?: 0 | 1;
  SAMSUNGPAY?: 0 | 1;
  LINEPAY?: 0 | 1;
  ImageUrl?: string;
  InstFlag?: "1" | string;
  CreditRed?: 0 | 1;
  UNIONPAY?: 0 | 1;
  WEBATM?: 0 | 1;
  VACC?: 0 | 1;
  BankType?: string;
  CVS?: 0 | 1;
  BARCODE?: 0 | 1;
  ESUNWALLET?: 0 | 1;
  TAIWANPAY?: 0 | 1;
  CVSCOM?: 0 | 1;
  EZPAY?: 0 | 1;
  EZPWECHAT?: 0 | 1;
  EZPALIPAY?: 0 | 1;
  LgsType?: "B2C" | "C2C";

  CREDITAGREEMENT?: 1;
  ANDROIDPAYAGREEMENT?: 1;
  SAMSUNGPAYAGREEMENT?: 1;
  TokenTerm?: string;
  TokenLife?: string;
  TokenTermDemand?: string;
};
